language: android

jdk:
 - oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew clean check

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "W00XhTCYxNte0LLHVtKo+f56N74jsacJvuqoFmuaGQq4OoQxkPk24h68RwIomdcKNY9TkCnHpn2eCu8mtJDEN1smIaEfBV8yChpPvL8z71CXa+VafatLFihXyv3Re3542WTd5wzRgAf7Dq+YO562oPcx+xIiNdX4AP9M2nQVn7d2Lmqj5q0PpUhcspWmNLzvuv0mfisEq/08Q1mbu7GR4ZKovvEP4XZCmEwgn3jQv2kZYULwOTY3jFo2oMPtMwxP9/W88qnCRICge5abs/mPU4Juj32mt1uM6skEzCVoMM5Z9XpruzxGP5i4daaPMlnRXg9VTqIB6XB3pcdQaWy+WXu+94iYCcadoEMs0b34Trn+gtevCLk6JPUSNb+1BVHMFB6zbwymA0n367bCOnwaT3u7uu5NldOq3Xnk/1tN2DGIWDjWhLPQXJez6VFA8dQN3JrR+xyThghpqplmpzXWy9gIbWY8djfihEddDW1C/wo4BEElfpaueu89hTKoeTkyq9yvjAXV/blEviwLQPpzJIaruA4rZfPMOUddO06FpOUq2R9C4OebgwJI5bVjSInPUyPVoFPnwNVbVZDB0WADmNeXHN20sjg0C5oNICouZn28whFFfqc/bzmmqM6I6ji2Yg9NylTYNavgukm5FwYb5Z4ugNI6dbdnlhoo+LpsV8s="
    - secure: "lsdq5l6XAJhRtTIga5bQVpkNXOhx1FjwC2q5n5w2/xTDXXW810IsH2BNLCahULx+yLTyXB3+VqwausfeNmeSJXWRMLW1HwoTYb7MEnbPQK8K373tLLs7L5IOTyIuIKD16LQC+1ceZzLyCLpKtbty06jnZ33kdmd0u+3XKTo23nNrfLXPiFoou9rXx+Zq8e274Pe6pjCa+7tBWTIrGkhO5VGRNi3n+esDxUoKjhPQklqsAZJx6yd+6GHGz37DsqIVleOHHgYQPds6D5CZOTjCOJo7AAGL4pu9R0J2fVESsltb/oHMz50jAdXZqx1bkfA+Z+o9uEFecTFrZ+PxvlzxApa77V/MS4zL1kwjV0X0YR4QTgLQJZBTKmkq3OC4yLKgAGrdD2shKfY/R4mrlaZLdooZplM2WgkKxOLroMvwtDzEeuJK79c0PsyPM9NMvbbHcII+ljhUHzU3fF5ALMatLFrzUD/2u72E+gt1RM6wRV6m0GHagwfLNdPG7s4dAjtpJMggIGLVWH8wUxf7KlOrfprHvyU3qNl/VnnPmgYq8AWh3+KNnaaluLTsXp14oM4iC6XVXD4+GnjI5Dna2qYztmAR8jX1cKhkAMAEQtjZMvhPbZfRQDP0+otTY7OfzqzHEg9nk8fiK/bCbsC87s/zEqZk4xqP+lz7MerSGaxLWGU="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
